version: '3'
services:
  api:
    build:
      context: .
      dockerfile: DockerfileApi
    ports:
      - 5000:5000
      - 8089:8089

  front:
    build:
      context: .
      dockerfile: DockerfileFront
    volumes:
      - /home/ubuntu/ATIVA/dB:/front/db
    ports:
      - 80:80